import "./globals.css";

export const metadata = {
  title: 'Home Page',
  description: 'Generated by Next.js',
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}